sudo: false

language: python

matrix:
  include:
  - python: 3.3
    env: TESTENV=unittest
  - python: 3.6
    env: TESTENV=documents

install:
  - pip install flake8
  - pip install flake8-docstrings
  - pip install flake8-mutable
  - pip install flake8-builtins
  - pip install pep8-naming
  - pip install pytest
  - pip install mkdocs-material
  - pip install pymdown-extensions
  - pip install pygments

addons:
  apt:
    packages:
      - aspell
      - aspell-en

script:
  - if [ $TESTENV = unittest ]; then py.test .; fi
  - if [ $TESTENV = unittest ]; then flake8 .; fi
  - if [ $TESTENV = documents ]; then python tests/spellcheck.py; fi
  - if [ $TESTENV = documents ]; then mkdocs build --clean --verbose --strict; fi

deploy:
  - provider: pages
    github_token: $GITHUB_TOKEN
    name: $GITHUB_USER
    email: $GITHUB_EMAIL
    skip_cleanup: true
    local_dir: site
    on:
      tags: true
      repo: facelessuser/BracketHighlighter
      condition: "$TESTENV = documents"
